version: '3.8'

services: 
  node_backend:
    container_name: fat_cat
    image: fat_cat_task
    build: 
      context: .
      args: 
       NODE_ENV: development
    ports:
      - "8000:8000"
    env_file:
     - ./config/.env 

    volumes:
     - ./:/app
     - /app/node_modules
      
    depends_on: 
      - postgres_db

  postgres_db: 
    container_name: postgres_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file:
     - ./config/.env 
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
